name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify script syntax
        run: |
          bash -n status-check.sh

  test:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Run Tests
        run: |
          echo "Running tests" && exit 0

  package:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: .
