name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      PROD_DOMAIN: ${{ vars.PROD_DOMAIN }}

    steps:
      - name: Push to Production
        run: echo "Deploying to $PROD_DOMAIN"
